# Application Configurations
spring.application.name=alert-service
server.port=8081
spring.profiles.active=ingestor
server.servlet.context-path=/api

# Kafka Configurations
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.properties[max.block.ms]=5000
alerts.kafka.raw-topic=raw-alerts
